import Head from 'next/head'
import { Inter } from '@next/font/google'
import Navbar from './components/Navbar'
import Question from './components/Question'
import Footer from './components/Footer'
import Tabs from './components/Tabs'
import Panel from './components/Panel'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <div className='flex flex-row'>
        <div className='w-4/5'>
        <Tabs />
      <Question />
      {/* <Footer />   */}
        </div>
        <div className='w-60 ml-4'>
          <Panel />
        </div>
      </div>     
    </>
  )
}
